In [13]:
import pandas as pd 
import numpy as np 

In [18]:
#2--构造评分矩阵
R=np.array([[4,0,2,0,1],
            [2,3,2,0,1],
            [4,3,2,1,1],
            [1,0,2,2,1],
            [4,1,2,0,1],
            [4,3,2,1,1]])

In [35]:
#3--设定超参数
K=5 #隐性特征的维度
max_iter=5000 #最大迭代次数
alpha=0.0002 #步长
lamda=0.004 #正则化系数


In [36]:
#4--构造LFM梯度下降算法的函数
def LFM_grad_desc(R,K=5,max_iter=1000,alpha=0.001,lamda=0.002):
    #基本维度参数定义
    M=len(R)
    N=len(R[0])
    #P,Q初始值，随机生成
    P=np.random.rand(M,K)
    Q=np.random.rand(N,K)
    #把Q进行转置
    Q=Q.T
    #开始迭代
    for step in range(max_iter):
        #对所有的用户u，物品i做遍历，对应的特征向量Pu,Qi梯度下降
        for u in range(M):
            for i in range(N):
                #对于每一个大于0的评分，求出预测评分误差
                if R[u][i]>0:
                    eui=np.dot(P[u,:],Q[:,i])-R[u][i]
                    #带入公式，按照梯度下降算法更新当前的Pu,Qi
                    for k in range(K):
                        P[u][k]=P[u][k]-alpha*(2*eui*Q[k][i]+2*lamda*P[u][k])
                        Q[k][i]=Q[k][i]-alpha*(2*eui*P[u][k]+2*lamda*Q[k][i])
        #u,i遍历完成，所有特征向量更新完成，可以得到P，Q,可以计算育成评分矩阵
        predR=np.dot(P,Q)
        #计算当前损失函数
        cost=0
        for u in range(M):
            for i in range(N):
                if R[u][i]>0:
                    cost=cost+(np.dot(P[u,:],Q[:,i])-R[u][i])**2
                    #加上正则化项
                    for k in range(K):
                        cost=cost+lamda*(P[u][k]**2+Q[k][i]**2)
        if cost<0.001:
            break
    return P,Q.T,cost

In [37]:
#5--调用LFM梯度下降函数
P,Q,cost=LFM_grad_desc(R,K,max_iter,alpha,lamda)
predR=P.dot(Q.T)
print(P)
print(Q)
print(cost)
print(R)
print(predR)

[[ 1.21397664  0.44185198  0.55988866  0.87119203  0.30119205]
 [ 0.28312504  1.02412214  0.23689556  0.96806516  0.06080651]
 [ 1.02965976  0.73950381  0.43210785  0.7350411   0.81013375]
 [-0.46262588  0.91098927  0.68737953  1.15827473 -0.02180266]
 [ 1.4577801   0.17013311  0.82600175  0.21954573  0.20607077]
 [ 0.94932986  0.70720916  0.71141918  0.67531287  0.67739028]]
[[ 1.92781321  0.64717059  1.06005517  0.54171268  0.80153764]
 [ 0.05027905  1.45090959  0.46399309  1.4494197   0.69686971]
 [ 0.50512302  0.78934434  0.70205524  0.8084648   0.14040347]
 [-0.3719581   0.61593327  0.45223151  0.82362557  0.11903821]
 [ 0.22205454  0.38193343  0.59794631  0.3157368  -0.03953677]]
0.8744054346649918
[[4 0 2 0 1]
 [2 3 2 0 1]
 [4 3 2 1 1]
 [1 0 2 2 1]
 [4 1 2 0 1]
 [4 3 2 1 1]]
[[3.93313921 2.43452386 2.10167018 0.82719159 1.03626965]
 [2.03286816 3.05556873 1.90889581 1.4371734  0.89891621]
 [3.96916874 2.95515927 2.11519202 0.96974301 0.9695086 ]
 [1.03634588 3.28107464 1.9013428