In [1]:
import tensorflow as tf 
from tensorflow import keras
from tensorflow.keras import datasets #kerass提供的数据集

### 一、加载数据

In [2]:
#加载数据集
(x,y),_=datasets.mnist.load_data()

11493376/11490434 [==============================] - 2s 0us/step


### 二、将数据转换成tensor

In [4]:
#转换成tensor
x=tf.convert_to_tensor(x,dtype=tf.float32)
y=tf.convert_to_tensor(y,dtype=tf.int32)

### 三、查看数据形状

In [5]:
x.shape

TensorShape([60000, 28, 28])

In [6]:
y.shape

TensorShape([60000])

In [7]:
x.dtype

tf.float32

In [8]:
y.dtype

tf.int32

In [9]:
#查看最小值
tf.reduce_min(x)

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [10]:
#查看最大值
tf.reduce_max(x)

<tf.Tensor: shape=(), dtype=float32, numpy=255.0>

In [11]:
#查看最小值
tf.reduce_min(y)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [12]:
#查看最大值
tf.reduce_max(y)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

### 四、数据缩放

In [14]:
#通过刚刚查看数据的最大最小值，利用数据的最大值，将数据缩放到0~1之间有利于tensorflow训练
x=tf.convert_to_tensor(x,dtype=tf.float32)/255
#y值之后会做one-hot编码，所以这里不用缩放
# y=tf.convert_to_tensor(y,dtype=tf.int32)/9

### 五、创建一个数据集

In [16]:
#创建一个数据集，指定一次取出的数据的多少，这里一次取128
train_db=tf.data.Dataset.from_tensor_slices((x,y)).batch(128)

In [17]:
train_iter=iter(train_db)
sample=next(train_iter)

In [19]:
sample[0].shape

TensorShape([128, 28, 28])

In [22]:
sample[1].shape

TensorShape([128])

In [24]:
#截取正太分布的某一个范围的数据
#[b,784]=>[b,256]=>[b,128]=>[b,10]
#w的第一个参数是输入，第二个参数是输出
#b的参数要w的输出保持一致
w1=tf.random.truncated_normal([784,256])
b1=tf.zeros([256])
w2=tf.random.truncated_normal([256,128])
b2=tf.zeros([128])
w3=tf.random.truncated_normal([128,10])
b3=tf.zeros([10])

In [ ]:
#前向运算
# 使用公式h1=x@w1+b1
for (x,y) in train_db:
    #x:[128,28,28]
    #y:[128]
    x=tf.reshape(x,[-1,28*28]) #维度变换[b,28,28]=>[b,28*28]
    h1=x@w1+tf.broadcast_to(b1,[x.shape[0],256]) #[b,784]@[784,256]+[256]=>[b,256]+[256]矩阵相乘